spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/ecommerce
  datasource:
    url: jdbc:postgresql://localhost:5432/eticaret_db?currentSchema=siparis_schema
    username: eticaret
    password: eticaret
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect:
    application:
      name: siparis_service
server:
  port: 8083

