server:
  port: 8081

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      routes:
        - id: urun-service
          uri: http://localhost:8084
          predicates:
            - Path=/urun/**
          filters:
            - TokenRelay=
        - id: siparis-service
          uri: http://localhost:8083
          predicates:
            - Path=/siparis/**
          filters:
            - TokenRelay=
        - id: kullanici-service
          uri: http://localhost:8082
          predicates:
            - Path=/kullanici/**
          filters:
            - TokenRelay=

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/ecommerce
