spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/eticaret_db?currentSchema=kullanici_schema
    username: eticaret
    password: eticaret
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: kullanici_service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/ecommerce
server:
  port: 8082